unit GrammarSymbols;

interface

Type 

	GrammarSymbol = (T_PROGRAM, IDENTIFIER, SEMI, T_BEGIN, T_END, ASSIG, 
	PLUS, MINUS, MULT, DIVI,
	OPPAR, CLPAR, OPBRA, CLBRA,
	CONSTANT, COMMA, 
	FIRST, REST,CONS,
	READINT, READLIST, WRITEINT, WRITELIST,
	T_STRING,
	T_IF, NEG, 
	NULL,
	GT, LT, GTE, LTE, EQ,
	T_AND, T_OR,
	T_ELSE, T_THEN, 
	T_ENDIF, 
	T_WHILE, T_DO, T_ENDWHILE,EPSILON, T_EOF,   {agregar error} 
	S,BODY,RRSENT,SENT,ASIG,EXPR, EXPARIT, RRTERM, 
	SUMOP, TERM, RRFACTOR, MULTOP, FACTOR, V_LIST, LISTCONST, RRINTCONST,
	V_REST, LISTARG, LISTID, V_CONS, V_READ, V_WRITE, IARG, OARG, OARGL, CONDITIONAL, CONDITION,
	V_NEG, C, RELOP, LOG, LOGOP, CLOSEIF, V_ELSE, V_ENDIF, CYCLE);
	
implementation
begin

end.



	

